
#Development environment/properties configuration

server:
  port: 8083



#  Database configuration
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/authdb
    username: admin
    password: admin

   #    hikari:
    #      pool-name: HikariCP
    #      maximum-pool-size: 5
    #      connection-timeout: 10000
    #      idle-timeout: 600000
    #      max-lifetime: 1800000
    #      validation-timeout: 1800000
    #      leak-detection-threshold: 0
    #      initialization-fail-timeout: -1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG


security:
  jwt:
    secret:${JWT_SECRET:secretKeyToGenerateJWTs}
    issuer:${JWT_ISSUER:com.creationix.auth}
    access-ttl-seconds:${JWT_ACCESS_TTL_SECONDS:600}
    refresh-ttl-seconds:${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name:${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure:${JWT_COOKIE_SECURE:true}
    cookie-http-only:${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site:${JWT_COOKIE_SAME_SITE:lax}
    cookie-domain:${JWT_COOKIE_DOMAIN:localhost}

